[global_tags]

[agent]
  flush_interval = "1s"
  round_interval = true
  metric_batch_size = 5000
  metric_buffer_limit = 200000
  collection_jitter = "0s"
  omit_hostname = true
  precision= "1ns"
#  debug = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics=["m2-data"]
  data_format = "json_v2"
  qos = 1
  
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name_path = "reference.MeasurementName"
    timestamp_path = "reference.Timestamp"
    timestamp_format = "unix_ns"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "reference.stats"
      tags = ["info"]

[[processors.starlark]]
order = 1
  source = '''
load("logging.star", "log")

state = {
  "last": None,
  "count": 1
}

def apply(metric):
  if "info" in metric.tags:
    last = state["last"]
    state["last"] = deepcopy(metric)
    if last != None:
      #log.debug("debug: {} {} {}".format(metric.time, last.time, state["count"]))
      if last.time == metric.time:
        metric.time = metric.time+state["count"]
        state["count"] = state["count"] + 1
        #log.debug("debug2: {}".format(metric.time))
      else:
        state["count"] = 1
  return metric
'''

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database="ratt"

# # Send telegraf metrics to file(s)
# [[outputs.file]]
  # ## Files to write to, "stdout" is a specially handled file.
  # files = ["stdout"]
  # ## Data format to output.
  # ## Each data format has it's own unique set of configuration options, read
  # ## more about them here:
  # ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  # data_format = "influx"
