---
#
# Copyright (C) 2024 Linutronix GmbH
# Author Kurt Kanzenbach <kurt@linutronix.de>
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Sample reference YAML configuration file for Intel Comet Lake platforms with
# i225 NIC(s).
#
Application:
  ApplicationClockId: CLOCK_TAI
  ApplicationBaseStartTimeNS: 0
  ApplicationBaseCycleTimeNS: 31250
  ApplicationTxBaseOffsetNS: 25000
  ApplicationRxBaseOffsetNS: 18750
  ApplicationLinkSpeed: 0 # 0=AutoNeg or link speed in Mbps 100, 1000, 2500, 10000, 100000, etc.
  ApplicationLinkHalfDuplex: false # false=full duplex, true=half duplex for 10Mbps or 100Mbps
  ApplicationWaitTimeSeconds: 0 # Need to be 8 or higher as a power of 2, default: 8
Log:
  LogThreadPeriodNS: 500000000
  LogThreadPriority: 1
  LogThreadCpu: 15
  LogFile: /var/log/mirror-T31.log
  LogLevel: Debug
LogViaMQTT:
   LogViaMQTT: True
   LogViaMQTTThreadCpu: 16
   LogViaMQTTThreadPriority: 1
   LogViaMQTTThreadPeriodNS: 1000000
   LogViaMQTTBrokerIP: 127.0.0.1
   LogViaMQTTBrokerPort: 1883
   LogViaMQTTMeasurementName: reference
TSNHigh:
  TsnHighEnabled: true
  TsnHighTxTimeEnabled: false
  TsnHighTxTimeOffsetNS: 0
  TsnHighVid: 100
  TsnHighNumFramesPerCycle: 4
  TsnHighPayloadPattern: |
    TsnHighPayloadPattern
  TsnHighFrameLength: 128
  TsnHighLPortID: 1:0
  TsnHighThreadCpu: 17
  TsnHighDestination: 6C:FE:54:A0:84:F0
TSNLow:
  TsnLowEnabled: false
  TsnLowTxTimeEnabled: false
  TsnLowTxTimeOffsetNS: 0
  TsnLowVid: 101
  TsnLowNumFramesPerCycle: 8
  TsnLowPayloadPattern: |
    TsnLowPayloadPattern
  TsnLowFrameLength: 128
  TsnLowLPortID: 1:1
  TsnLowThreadCpu: 18
  TsnLowDestination: 6C:FE:54:A0:84:F0
RTC:
  RtcEnabled: false
  RtcVid: 102
  RtcNumFramesPerCycle: 8
  RtcPayloadPattern: |
    RtcPayloadPattern
  RtcFrameLength: 128
  RtcLPortID: 1:2
  RtcThreadCpu: 19
  RtcDestination: 6C:FE:54:A0:84:F0
RTA:
  RtaEnabled: false
  RtaVid: 103
  RtaBurstPeriodNS: 200000000
  RtaNumFramesPerCycle: 8
  RtaPayloadPattern: |
    RtaPayloadPattern
  RtaFrameLength: 200
  RtaLPortID: 1:3
  RtaThreadCpu: 20
  RtaDestination: 6C:FE:54:A0:84:F0
DCP:
  DcpEnabled: false
  DcpVid: 104
  DcpBurstPeriodNS: 2000000000
  DcpNumFramesPerCycle: 8
  DcpPayloadPattern: |
    DcpPayloadPattern
  DcpFrameLength: 200
  DcpLPortID: 1:4
  DcpThreadCpu: 21
  DcpDestination: 6C:FE:54:A0:84:F0
LLDP:
  LldpEnabled: false
  LldpBurstPeriodNS: 5000000000
  LldpNumFramesPerCycle: 8
  LldpPayloadPattern: |
    LldpPayloadPattern
  LldpFrameLength: 200
  LldpLPortID: 1:6
  LldpThreadCpu: 22
  LldpDestination: 01:80:c2:00:00:0e
UDPHigh:
  UdpHighEnabled: false
  UdpHighBurstPeriodNS: 1000000000
  UdpHighNumFramesPerCycle: 8
  UdpHighPayloadPattern: |
    UdpHighPayloadPattern
  UdpHighFrameLength: 1400
  UdpHighLPortID: 1:6
  UdpHighThreadCpu: 23
  UdpHighPort: 6666
  UdpHighSrcPort: 7777
  UdpHighDestination: 10.10.1.1
  UdpHighSource: 10.10.1.2
  UdpHighMacDestination: 6C:FE:54:A0:84:F0
UDPLow:
  UdpLowEnabled: false
  UdpLowBurstPeriodNS: 1000000000
  UdpLowNumFramesPerCycle: 8
  UdpLowPayloadPattern: |
    UdpLowPayloadPattern
  UdpLowFrameLength: 1400
  UdpLowLPortID: 1:6
  UdpLowThreadCpu: 24
  UdpLowPort: 6667
  UdpLowSrcPort: 7778
  UdpLowDestination: 10.10.1.1
  UdpLowSource: 10.10.1.2
  UdpLowMacDestination: 6C:FE:54:A0:84:F0
L2:
  L2Name: L2
  L2Enabled: false
  L2TxTimeEnabled: true
  L2TxTimeOffsetNS: 300000
  L2Vid: 400
  L2Pcp: 6
  L2EtherType: 0x22f1
  L2NumFramesPerCycle: 8
  L2PayloadPattern: |
    L2PayloadPattern
  L2FrameLength: 128
  L2LPortID: 1:6
  L2ThreadCpu: 25
  L2Destination: 6C:FE:54:A0:84:F0
Stats:
  StatsHistogramEnabled: false
Debug:
  DebugStopTraceOnOutlier: false
  DebugStopTraceOnError: false
  DebugMonitorMode: false
  DebugMonitorDestination: 44:44:44:44:44:44
