---
#
# Copyright (C) 2024 Linutronix GmbH
# Author Kurt Kanzenbach <kurt@linutronix.de>
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Sample reference YAML configuration file for Intel Comet Lake platforms with
# i225 NIC(s).
#
Application:
  ApplicationClockId: CLOCK_TAI
  ApplicationBaseStartTimeNS: 0
  ApplicationBaseCycleTimeNS: 1000000
  ApplicationTxBaseOffsetNS: 800000
  ApplicationRxBaseOffsetNS: 600000
  ApplicationLinkSpeed: 0 # 0=AutoNeg or link speed in Mbps 100, 1000, 2500, 10000, 100000, etc.
  ApplicationLinkHalfDuplex: false # false=full duplex, true=half duplex for 10Mbps or 100Mbps
  ApplicationWaitTimeSeconds: 0 # Need to be 8 or higher as a power of 2, default: 8
Log:
  LogThreadPeriodNS: 500000000
  LogThreadPriority: 1
  LogThreadCpu: 15
  LogFile: /var/log/mirror-T1000.log
  LogLevel: Info
LogViaMQTT:
   LogViaMQTT: true
   LogViaMQTTThreadCpu: 16
   LogViaMQTTThreadPriority: 1
   LogViaMQTTThreadPeriodNS: 1000000
   LogViaMQTTBrokerIP: 127.0.0.1
   LogViaMQTTBrokerPort: 1883
   LogViaMQTTMeasurementName: reference
PKTHandler:
  PktHandlerEnabled: true
  PktHandlerThreadCpu: 17
TSNHigh:
  TsnHighEnabled: true
  TsnHighTxTimeEnabled: false
  TsnHighTxTimeOffsetNS: 0
  TsnHighVid: 100
  TsnHighNumFramesPerCycle: 512
  TsnHighPayloadPattern: |
    TsnHighPayloadPattern
  TsnHighFrameLength: 128
  TsnHighThreadCpu: 18
  TsnHighDestination: 6c:fe:54:a0:84:f0
  TsnHighIgnoreRxErrors: true
TSNLow:
  TsnLowEnabled: true
  TsnLowTxTimeEnabled: false
  TsnLowTxTimeOffsetNS: 0
  TsnLowVid: 101
  TsnLowNumFramesPerCycle: 8
  TsnLowPayloadPattern: |
    TsnLowPayloadPattern
  TsnLowFrameLength: 128
  TsnLowThreadCpu: 19
  TsnLowDestination: 6c:fe:54:a0:84:f0
RTC:
  RtcEnabled: false
  RtcVid: 102
  RtcNumFramesPerCycle: 8
  RtcPayloadPattern: |
    RtcPayloadPattern
  RtcFrameLength: 128
  RtcThreadCpu: 20
  RtcDestination: 6c:fe:54:a0:84:f0
RTA:
  RtaEnabled: false
  RtaVid: 103
  RtaBurstPeriodNS: 200000000
  RtaNumFramesPerCycle: 8
  RtaPayloadPattern: |
    RtaPayloadPattern
  RtaFrameLength: 200
  RtaThreadCpu: 21
  RtaDestination: 6c:fe:54:a0:84:f0
DCP:
  DcpEnabled: false
  DcpVid: 104
  DcpBurstPeriodNS: 2000000000
  DcpNumFramesPerCycle: 8
  DcpPayloadPattern: |
    DcpPayloadPattern
  DcpFrameLength: 200
  DcpThreadCpu: 22
  DcpDestination: 6c:fe:54:a0:84:f0
LLDP:
  LldpEnabled: false
  LldpBurstPeriodNS: 5000000000
  LldpNumFramesPerCycle: 8
  LldpPayloadPattern: |
    LldpPayloadPattern
  LldpFrameLength: 200
  LldpThreadCpu: 23
  LldpDestination: 01:80:c2:00:00:0e
UDPHigh:
  UdpHighEnabled: true
  UdpHighBurstPeriodNS: 1000000000
  UdpHighNumFramesPerCycle: 8
  UdpHighPayloadPattern: |
    UdpHighPayloadPattern
  UdpHighFrameLength: 1400
  UdpHighThreadCpu: 24
  UdpHighPort: 6666
  UdpHighSrcPort: 7777
  UdpHighDestination: 10.10.1.1
  UdpHighSource: 10.10.1.2
  UdpHighMacDestination: 6c:fe:54:a0:84:f0
UDPLow:
  UdpLowEnabled: false
  UdpLowBurstPeriodNS: 1000000000
  UdpLowNumFramesPerCycle: 8
  UdpLowPayloadPattern: |
    UdpLowPayloadPattern
  UdpLowFrameLength: 1400
  UdpLowThreadCpu: 25
  UdpLowPort: 6667
  UdpLowSrcPort: 7778
  UdpLowDestination: 10.10.1.1
  UdpLowSource: 10.10.1.2
  UdpLowMacDestination: 6c:fe:54:a0:84:f0
L2:
  L2Enabled: false
  L2TxTimeEnabled: false
  L2TxTimeOffsetNS: 300000
  L2Vid: 400
  L2Pcp: 6
  L2EtherType: 0x22f1
  L2NumFramesPerCycle: 8
  L2PayloadPattern: |
    L2PayloadPattern
  L2FrameLength: 128
  L2ThreadCpu: 26
  L2Destination: 6c:fe:54:a0:84:f0
Stats:
  StatsHistogramEnabled: false
Debug:
  DebugStopTraceOnOutlier: false
  DebugStopTraceOnError: false
  DebugMonitorMode: false
  DebugMonitorDestination: 44:44:44:44:44:44
